/*
 * generated by Xtext
 */
package transformation.ctllang2ctl.scoping;

import transformation.propositionallogiclang2propositionallogic.scoping.PropositionalLogicXtextScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class CtlXtextScopeProvider extends PropositionalLogicXtextScopeProvider {

}
