/*
* generated by Xtext
*/
package transformation.propositionallogiclang2propositionallogic.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PropositionalLogicXtextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("propositionallogiclang2propositionallogic/parser/antlr/internal/InternalPropositionalLogicXtext.tokens");
	}
}
