/*
* generated by Xtext
*/
package org.foam.xtext.plogic;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.ISetup;
import org.eclipse.emf.ecore.resource.Resource;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Generated from StandaloneSetup.xpt!
 */
@SuppressWarnings("all")
public class PropositionalLogicXtextStandaloneSetupGenerated implements ISetup {

	public Injector createInjectorAndDoEMFRegistration() {
		org.eclipse.xtext.common.TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new org.foam.xtext.plogic.PropositionalLogicXtextRuntimeModule());
	}
	
	public void register(Injector injector) {
	if (!EPackage.Registry.INSTANCE.containsKey("http://foam.org/models/plogicXtext")) {
		EPackage.Registry.INSTANCE.put("http://foam.org/models/plogicXtext", org.foam.xtext.plogic.propositionalLogicXtext.PropositionalLogicXtextPackage.eINSTANCE);
	}

	}
}
