/*
 * generated by Xtext
 */
package ltllang2ltl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LtlXtextRuntimeModule extends ltllang2ltl.AbstractLtlXtextRuntimeModule {

}
