/*
 * generated by Xtext
 */
package org.foam.xtext.ltl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LtlXtextRuntimeModule extends org.foam.xtext.ltl.AbstractLtlXtextRuntimeModule {

}
