/*
* generated by Xtext
*/
package transformation.propositionallogiclang2propositionallogic.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import transformation.propositionallogiclang2propositionallogic.parser.antlr.internal.InternalPropositionalLogicXtextParser;
import transformation.propositionallogiclang2propositionallogic.services.PropositionalLogicXtextGrammarAccess;

import com.google.inject.Inject;

public class PropositionalLogicXtextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PropositionalLogicXtextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected InternalPropositionalLogicXtextParser createParser(XtextTokenStream stream) {
		return new InternalPropositionalLogicXtextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RuleStart";
	}
	
	public PropositionalLogicXtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PropositionalLogicXtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
