<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceability_ucm_text" nsURI="traceability_ucm_text" nsPrefix="traceability_ucm_text">
  <eClassifiers xsi:type="ecore:EClass" name="UcmToTextTraces">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepLabels" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass traceability2.ecore#//TraceEntry">
        <eTypeArguments eClassifier="ecore:EClass ucm.ecore#//Step"/>
        <eTypeArguments eClassifier="ecore:EClass text.ecore#//StringWithOffset"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCaseNames" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass traceability2.ecore#//TraceEntry">
        <eTypeArguments eClassifier="ecore:EClass ucm.ecore#//UseCase"/>
        <eTypeArguments eClassifier="ecore:EClass text.ecore#//StringWithOffset"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
