/*
* generated by Xtext
*/
package org.foam.xtext.plogic;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PropositionalLogicXtextStandaloneSetup extends PropositionalLogicXtextStandaloneSetupGenerated{

	public static void doSetup() {
		new PropositionalLogicXtextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

