/*
 * generated by Xtext
 */
package org.foam.xtext.plogic;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PropositionalLogicXtextRuntimeModule extends org.foam.xtext.plogic.AbstractPropositionalLogicXtextRuntimeModule {

}
