/*
* generated by Xtext
*/
package ltllang2ltl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LtlXtextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ltllang2ltl/parser/antlr/internal/InternalLtlXtext.tokens");
	}
}
