/*
* generated by Xtext
*/
package transformation.ltllang2ltl.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import transformation.ltllang2ltl.services.LtlXtextGrammarAccess;

import com.google.inject.Inject;

public class LtlXtextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LtlXtextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected transformation.ltllang2ltl.parser.antlr.internal.InternalLtlXtextParser createParser(XtextTokenStream stream) {
		return new transformation.ltllang2ltl.parser.antlr.internal.InternalLtlXtextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RuleStart";
	}
	
	public LtlXtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LtlXtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
