/*
* generated by Xtext
*/
package transformation.propositionallogiclang2propositionallogic.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

import transformation.propositionallogiclang2propositionallogic.propositionalLogicXtext.PropositionalLogicXtextPackage;

public class AbstractPropositionalLogicXtextJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(PropositionalLogicXtextPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("propositionallogic"));
		return result;
	}

}
