package org.foam.cli.tools.report.pages;

import org.eclipse.xtend.lib.Data;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.util.ToStringHelper;

@Data
@SuppressWarnings("all")
public class PageTemplate {
  public CharSequence printPage(final CharSequence css, final CharSequence menu, final CharSequence content) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html lang=\"en\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta charset=\"utf-8\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<title>FOAM tool</title>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta name=\"description\" content=\"\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta name=\"author\" content=\"\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Le styles -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link href=\"../assets/css/bootstrap.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<style type=\"text/css\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("body {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("padding-top: 60px;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("padding-bottom: 40px;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".sidebar-nav {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("padding: 9px 0;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("@media (max-width: 980px) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("/* Enable use of floated navbar text */");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(".navbar-text.pull-right {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("float: none;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("padding-left: 5px;");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("padding-right: 5px;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".scenario { counter-reset: list1 0; list-style-type: none; margin-left: 0px }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".scenario li { counter-increment: list1 }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".scenario li:before { margin-right: 10px }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".main li:before { content: counter(list1) \'.\' }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".annot { font-weight: bold; color: blue }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".loop { font-weight: bold; color: green }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".usecase-header-block { margin-bottom: 14px }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(".tracecell { padding-left: 10px }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("h2 { font-size: 24.5px }");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append(css, "\t\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link href=\"../assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("<!--[if lt IE 9]>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<script src=\"../assets/js/html5shiv.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<![endif]-->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Fav and touch icons -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"../assets/ico/apple-touch-icon-144-precomposed.png\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"../assets/ico/apple-touch-icon-114-precomposed.png\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"../assets/ico/apple-touch-icon-72-precomposed.png\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link rel=\"apple-touch-icon-precomposed\" href=\"../assets/ico/apple-touch-icon-57-precomposed.png\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<link rel=\"shortcut icon\" href=\"../assets/ico/favicon.png\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</head>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<body>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"navbar navbar-inverse navbar-fixed-top\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"navbar-inner\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"container-fluid\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<a class=\"brand\" href=\"#\">FOAM tool report</a>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"nav-collapse collapse\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<p class=\"navbar-text pull-right\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<!-- Logged in as <a href=\"#\" class=\"navbar-link\">Username</a> -->");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div><!--/.nav-collapse -->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"container-fluid\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"row-fluid\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span3\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"well sidebar-nav\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<ul class=\"nav nav-list\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("<!--<li class=\"nav-header\">Sidebar</li>-->");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(menu, "\t\t\t\t\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div><!--/.well -->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div><!--/span-->");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span9\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append(content, "\t\t\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("<div class=\"uc-image\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div><!--/span-->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div><!--/row-->  ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<hr>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<footer>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<p>FOAM tool report 2013</p>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</footer>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div><!--/.fluid-container-->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Le javascript");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("================================================== -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!-- Placed at the end of the document so the pages load faster -->");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/jquery.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap.min.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<!--");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-transition.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-alert.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-modal.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-dropdown.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-scrollspy.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-tab.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-tooltip.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-popover.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-button.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-collapse.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-carousel.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<script src=\"../assets/js/bootstrap-typeahead.js\"></script>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("-->");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    return _builder;
  }
  
  public PageTemplate() {
    super();
  }
  
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    return result;
  }
  
  @Override
  public boolean equals(final Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    PageTemplate other = (PageTemplate) obj;
    return true;
  }
  
  @Override
  public String toString() {
    String result = new ToStringHelper().toString(this);
    return result;
  }
}
