/*
 * generated by Xtext
 */
package transformation.ctllang2ctl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CtlXtextRuntimeModule extends transformation.ctllang2ctl.AbstractCtlXtextRuntimeModule {

}
