/*
 * generated by Xtext
 */
package transformation.ltllang2ltl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LtlXtextRuntimeModule extends transformation.ltllang2ltl.AbstractLtlXtextRuntimeModule {

}
