/*
 * generated by Xtext
 */
package transformation.propositionallogiclang2propositionallogic;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PropositionalLogicXtextRuntimeModule extends AbstractPropositionalLogicXtextRuntimeModule {

}
