/*
* generated by Xtext
*/
package transformation.ctllang2ctl.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import transformation.ctllang2ctl.services.CtlXtextGrammarAccess;

import com.google.inject.Inject;

public class CtlXtextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CtlXtextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected transformation.ctllang2ctl.parser.antlr.internal.InternalCtlXtextParser createParser(XtextTokenStream stream) {
		return new transformation.ctllang2ctl.parser.antlr.internal.InternalCtlXtextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RuleStart";
	}
	
	public CtlXtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CtlXtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
