/*
* generated by Xtext
*/
package org.foam.xtext.plogic.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PropositionalLogicXtextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/foam/xtext/plogic/parser/antlr/internal/InternalPropositionalLogicXtext.tokens");
	}
}
