/*
* generated by Xtext
*/
package org.foam.xtext.plogic.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.foam.xtext.plogic.services.PropositionalLogicXtextGrammarAccess;

public class PropositionalLogicXtextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PropositionalLogicXtextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.foam.xtext.plogic.parser.antlr.internal.InternalPropositionalLogicXtextParser createParser(XtextTokenStream stream) {
		return new org.foam.xtext.plogic.parser.antlr.internal.InternalPropositionalLogicXtextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RuleStart";
	}
	
	public PropositionalLogicXtextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PropositionalLogicXtextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
