/*
* generated by Xtext
*/
package transformation.ctllang2ctl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractCtlXtextJavaValidator extends transformation.propositionallogiclang2propositionallogic.validation.PropositionalLogicXtextJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("propositionallogic"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("ctl"));
		return result;
	}

}
