/*
 * generated by Xtext
 */
package org.foam.xtext.plogic.ui.contentassist

import org.foam.xtext.plogic.ui.contentassist.AbstractPropositionalLogicXtextProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PropositionalLogicXtextProposalProvider extends AbstractPropositionalLogicXtextProposalProvider {
}
